// TruthScan — AI text detection controller
const { tryModelsInOrder } = require('../lib/modelHelpers');

const buildDetectionPrompt = (text) => `
You are an AI detector. I will give you a piece of text.
Estimate how much of it is likely generated by an AI like ChatGPT, Gemini, etc.
Just return a number between 0 to 100. No explanation.

Text:
"""${text}"""
`;

exports.handleAIDetection = async (req, res) => {
  const { text } = req.body;
  if (!text) return res.status(400).json({ error: 'Text is required' });

  try {
    console.log('[TruthScan Detect] Running AI text detection...');
    const rawResponse = await tryModelsInOrder(buildDetectionPrompt(text));
    const score = parseInt(rawResponse.match(/\d+/)?.[0] ?? '0', 10);

    console.log(`[TruthScan Detect] AI likelihood: ${score}%`);
    res.json({
      textPreview: `${text.slice(0, 100)}...`,
      aiLikelihoodPercent: score,
    });
  } catch (err) {
    console.error('[TruthScan Detect] All models exhausted:', err.message);
    res.status(500).json({ error: 'AI detection failed. All models exhausted.' });
  }
};